#Expyriment 1.0.0 (Python 3.12.3), .xpe-file, coding: UTF-8
#date: Sun Sep 21 2025 12:03:18
#sha1: 6c8941
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Linux', node='LeoSurface7', release='6.6.87.2-microsoft-standard-WSL2', version='#1 SMP PREEMPT_DYNAMIC Thu Jun  5 18:31:42 UTC 2025', machine='aarch64')
Time,Type,Event,Value,Detail,Detail2
143,stderr,received,'Traceback (most recent call last):'
143,stderr,received,'  File "/home/leo/cogsup-prog/CORE1/Week-2/Exercises/labeled_shapes.py", line 13, in <module>'
144,stderr,received,'    t.add_vertices((0,50))'
144,stderr,received,'  File "/home/leo/projects/exp/.venv/lib/python3.12/site-packages/expyriment/stimuli/_shape.py", line 417, in add_vertices'
156,stderr,received,'    raise TypeError(type_error_message)'
156,stderr,received,'TypeError: The method add_vertices requires a list of tuples as argument.'
