#Expyriment 1.0.0 (Python 3.12.3), .xpe-file, coding: UTF-8
#date: Wed Sep 17 2025 19:27:00
#sha1: 6081bf
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Linux', node='LeoSurface7', release='6.6.87.2-microsoft-standard-WSL2', version='#1 SMP PREEMPT_DYNAMIC Thu Jun  5 18:31:42 UTC 2025', machine='aarch64')
Time,Type,Event,Value,Detail,Detail2
733,design,log,
#design: #exp: Square
#design: block_cnt,block_id,trial_cnt,trial_id
733,design,logged,
733,Experiment,started
733,Stimulus,presented,0
736,Stimulus,presented,1
780,stderr,received,'Traceback (most recent call last):'
780,stderr,received,'  File "/home/leo/cogsup-prog/CORE1/Week-2/Exercises/launching.py", line 24, in <module>'
780,stderr,received,'    square.move((350,0))'
780,stderr,received,'    ^^^^^^'
780,stderr,received,"NameError: name 'square' is not defined. Did you mean: 'square1'?"
