#Expyriment 1.0.0 (Python 3.12.3), .xpe-file, coding: UTF-8
#date: Wed Oct 01 2025 18:41:34
#sha1: 1e51dc
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Linux', node='LeoSurface7', release='6.6.87.2-microsoft-standard-WSL2', version='#1 SMP PREEMPT_DYNAMIC Thu Jun  5 18:31:42 UTC 2025', machine='aarch64')
Time,Type,Event,Value,Detail,Detail2
141,Stimulus,presented,0
1142,Stimulus,presented,1
1142,Stimulus,presented,2
1143,Stimulus,presented,3
1158,stderr,received,'Traceback (most recent call last):'
1158,stderr,received,'  File "/home/leo/Assignments/Week-4/Exercises/ternus2.py", line 49, in <module>'
1159,stderr,received,'    run_trial(50, 400)'
1159,stderr,received,'  File "/home/leo/Assignments/Week-4/Exercises/ternus2.py", line 28, in run_trial'
1159,stderr,received,'    c01.present(clear=False, update=False)'
1159,stderr,received,'    ^^^'
1159,stderr,received,"UnboundLocalError: cannot access local variable 'c01' where it is not associated with a value"
